[package]
name = "generate-patch"
version = "1.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
oozextract = "=0.5.5"
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"
sha2 = "=0.10.9"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
